str = 'FirstBit Solutions'

#print(str.capitalize())
#print(str.count('bit'))
#print(str.endswith('tions'))
#print(str.find('s'))
#print(str.index('s'))
#print(str.isalnum())
#print(str.isalpha())
#print(str.isdigit())
#print(str.islower())
#print(str.isspace())
#print(str.isupper())
#print(str.lower())
#print(str.upper)
#print(str.replace())
#print(str.swapcase())
#print(str.strip())
#print(str.startwith)
print(','.join(['a','b','c']))